# Project Euler 44
# Pentagonal Numbers
# https://projecteuler.net/problem=44
# Pentagonal numbers are generated by the formula $P_n = n(3n-1)/2$
# Find the pair of pentagonal numbers for which:
#   Their sum and difference are also pentagonal numbers
#   The absolute value of the difference between the two is minimised

# Let's just generate ourselves some pentagonal numbers to work with:
n = 1
pentagonal_numbers = []
def pentagonal(x: int) -> int:
    return x*((3*x)-1)/2
while n < 5000:
    pentagonal_numbers.append(pentagonal(n))
    n += 1

def test_pent(x: int) -> bin:
    if x <= 0:
        raise ValueError('Input cannot be 0 or negative')
    condition = (((24*x + 1)**0.5) + 1) / 6
    if condition % 1 == 0:
        return True
    else:
        return False

candidates = []
for pent1 in pentagonal_numbers:
    for pent2 in pentagonal_numbers:
        # Since we're iterating over the whole list, pent1-pent2 vs pent2-pent1 doesn't matter
        # We'll see the combo at some point, even if it isn't efficient
        if pent1 - pent2 > 0:
            if test_pent(pent1 + pent2) and test_pent(pent1 - pent2):
                candidates.append([pent1, pent2])
                break

# This is not a particularly robust way to get to a solution
# I haven't done any checks on minimisation or anything
# Pretty sure the size of the number means that 'proving' it's the smallest difference is kind of trivial though
# Anyway, it's the answer, I'll take it
print(candidates[0][0] - candidates[0][1])

